apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tinyfilemanager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-tinyfilemanager
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-tinyfilemanager
    spec:
      containers:
        - name: tinyfilemanager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: config-volume
              mountPath: /var/www/html/config.php
              subPath: config.php
      volumes:
        - name: config-volume
          configMap:
            name: tinyfilemanager-config
        - name: storage-volume
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}

            