apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tinyfilemanager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-tinyfilemanager
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-tinyfilemanager
spec:
  containers:
  - name: tinyfilemanager
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        volumeMounts:
            - name: storage-volume
              mountPath: /var/www/html # Asegúrate de que esta ruta sea correcta para tu uso
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: tinyfilemanager-pvc

            