replicaCount: 1

image:
  repository: tinyfilemanager/tinyfilemanager
  pullPolicy: IfNotPresent
  tag: "master"

service:
  type: ClusterIP
  port: 80

pvc:
  name: tinyfilemanager-pvc

volumes:
  name: pvc-5a9f01f3-477a-4c15-99a7-de7ad6ac1ac6